@Employee.API_HostAddress = https://localhost:7206

GET {{Employee.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Employee.API_HostAddress}}/api/departmentmaster/AddDepartment
Content-Type: application/json

{
  //DepartmentTbl
}

###

POST {{Employee.API_HostAddress}}/api/employeemaster/Login
Content-Type: application/json

{
  //LoginRequestDTO
}

###

GET {{Employee.API_HostAddress}}/api/employeemaster/GetAllEmployees

###

POST {{Employee.API_HostAddress}}/api/designationmaster/AddDesignation
Content-Type: application/json

{
  esignationName: "Quality Engineer",
  departmentId: "13"

}

###
